"""crear tablas iniciales

Revision ID: 34ec75105e68
Revises: 
Create Date: 2025-06-24 22:35:37.521000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ec75105e68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acquisitions', schema=None) as batch_op:
        batch_op.drop_index('idx_acquisitions_project_id')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index('idx_authors_email')

    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.drop_index('idx_deliverables_milestone_id')

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index('idx_milestones_project_id')

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index('idx_project_members_project_id')
        batch_op.drop_index('idx_project_members_user_id')

    with op.batch_alter_table('publication_authors', schema=None) as batch_op:
        batch_op.drop_index('idx_publication_authors_author_id')
        batch_op.drop_index('idx_publication_authors_publication_id')

    with op.batch_alter_table('publication_keywords', schema=None) as batch_op:
        batch_op.drop_index('idx_publication_keywords_keyword_id')
        batch_op.drop_index('idx_publication_keywords_publication_id')

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index('idx_publications_conference_id')
        batch_op.drop_index('idx_publications_doi')
        batch_op.drop_index('idx_publications_external_id')
        batch_op.drop_index('idx_publications_journal_id')
        batch_op.drop_index('idx_publications_project_id')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_refresh_tokens_user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_refresh_tokens_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index('idx_publications_project_id', ['project_id'], unique=False)
        batch_op.create_index('idx_publications_journal_id', ['journal_id'], unique=False)
        batch_op.create_index('idx_publications_external_id', ['external_id'], unique=False)
        batch_op.create_index('idx_publications_doi', ['doi'], unique=False)
        batch_op.create_index('idx_publications_conference_id', ['conference_id'], unique=False)

    with op.batch_alter_table('publication_keywords', schema=None) as batch_op:
        batch_op.create_index('idx_publication_keywords_publication_id', ['publication_id'], unique=False)
        batch_op.create_index('idx_publication_keywords_keyword_id', ['keyword_id'], unique=False)

    with op.batch_alter_table('publication_authors', schema=None) as batch_op:
        batch_op.create_index('idx_publication_authors_publication_id', ['publication_id'], unique=False)
        batch_op.create_index('idx_publication_authors_author_id', ['author_id'], unique=False)

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index('idx_project_members_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_project_members_project_id', ['project_id'], unique=False)

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index('idx_milestones_project_id', ['project_id'], unique=False)

    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.create_index('idx_deliverables_milestone_id', ['milestone_id'], unique=False)

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index('idx_authors_email', ['email'], unique=False)

    with op.batch_alter_table('acquisitions', schema=None) as batch_op:
        batch_op.create_index('idx_acquisitions_project_id', ['project_id'], unique=False)

    # ### end Alembic commands ###
